### ISSUE TITLE
Crafting "tool watch" needs non-existent tool

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [thhoney08/ZombieHighMod#1]
![image](https://github.com/thhoney08/ZombieHighMod/assets/3938423/237d8bbf-148b-424d-971c-97c3e665346a)

To craft the tool watch one needs a tool with fine metal sawing 2, except...it doesn't exist in-game.

**Comment by thhoney08** [comment]
Ok, gonna release the fixed version on febuary

**Comment by thhoney08** [comment]
Alright, fixed!
