### ISSUE TITLE
Remake weapons that use tazer action

### ISSUE THREAD

**Issue by Petrociaczhe** [thhoney08/ZombieHighMod#5]
weapon like powered staff no longer use tazer action and it is replaced by transform with shocking flag. stun knuckle and cattle prod might benefit from such change. while on this topic, the charge per use of powered staff on item remake should be removed since it no longer use that.

**Comment by thhoney08** [comment]
Ok, I will  remake them ASAP!

**Comment by thhoney08** [comment]
Done, thanks for the heads up!
